#StarGate Universe
##Project by Alemiz
#Website: https://github.com/Alemiz112

#Supports more connections
connections:
  default:
    address: 127.0.0.1
    port: 47007
    password: 123456789
    name: Lobby