# StarGate Universe
# Project by Alemiz
# Website: https://github.com/Alemiz112

# Supports more connections
connections:
  lobby1:
    address: 192.168.0.50
    port: 47007
    password: 123456789

# Enable debug logger
debug: true
# Default client will be used if no clientName specified in api functions
defaultClient: "lobby1"